services:
  web:
    build: .
    command: gunicorn planilha_trader.wsgi:application --bind 0.0.0.0:8032 --reload
    volumes:
      - .:/app
    ports:
      - "8032:8032"
    env_file:
      - .env