# Generated by Django 5.0.6 on 2026-04-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecaodia',
            name='capital_final',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Capital acumulado ao final do dia (calculado automaticamente)', max_digits=12, null=True),
        ),
    ]
