# Generated by Django 6.0.4 on 2026-04-23 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0003_operacao_data_cal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='operacao',
            index=models.Index(fields=['user', 'month', 'dia'], name='planilha_op_user_id_292333_idx'),
        ),
    ]
