# Generated by Django 5.0.6 on 2026-05-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0003_operacao_data_cal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='entrada',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='saida',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
