# Generated by Django 5.0.6 on 2026-05-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilha', '0004_alter_operacao_entrada_alter_operacao_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilhaconfig',
            name='plano_meta_semanal_wdo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='planilhaconfig',
            name='plano_meta_semanal_win',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
