# Generated by Django 5.0.6 on 2026-04-11 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('conteudo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diario_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('dia', models.IntegerField()),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda')], default='COMPRA', max_length=10)),
                ('ativo', models.CharField(choices=[('WIN', 'WIN - Índice'), ('WDO', 'WDO - Dólar'), ('BIT', 'BIT - Bitcoin')], default='WIN', max_length=10)),
                ('entrada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('contratos', models.IntegerField(default=1)),
                ('valor_ponto', models.DecimalField(decimal_places=2, default=0.2, max_digits=10)),
                ('pontos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('resultado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('GAIN', 'Gain'), ('LOSS', 'Loss'), ('ZERADA', 'Zerada')], default='GAIN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['month', 'dia', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Regra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('ordem', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordem', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanilhaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('banca_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('objetivo_diario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dias_uteis', models.IntegerField(default=20)),
                ('plano_meta_aprovacao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('plano_perda_max_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('plano_perda_diaria_aprovacao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('plano_risco1', models.CharField(blank=True, default='', max_length=100)),
                ('plano_start', models.CharField(blank=True, default='', max_length=20)),
                ('plano_capital', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('plano_meta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('plano_ativos', models.CharField(blank=True, default='WIN, WDO', max_length=100)),
                ('plano_maxentradas', models.IntegerField(default=5)),
                ('plano_stop', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('plano_diario', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('user', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ProjecaoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('dia', models.IntegerField()),
                ('realizado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('custo_op', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('imposto_retido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projecao_dias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['month', 'dia'],
                'unique_together': {('user', 'month', 'dia')},
            },
        ),
    ]
